---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dov-bear-cm
data:
  INSTANCE_NAME: k8s-dov-bear configmap
---
apiVersion: v1
kind: Secret
metadata:
  name: dov-bear-secrets
type: Opaque
data:
  INSTANCE_NAME: azhzLWRvdi1iZWFyIFNFQ1JFVA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-bear-deploy
  labels:
    name: dov-bear-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dov-bear-po
  template:
    metadata:
      name: dov-bear-po
      labels:
        name: dov-bear-po
        dept: eng
    spec:
      containers:
        - name: dov-bear-container
          image: chukmunnlee/dov-bear:v2
          imagePullPolicy: IfNotPresent
          ports:
            - name: dov-port
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTP
          envFrom:
            - secretRef:
                name: dov-bear-secrets
          resources:
            requests:
              memory: 128Mi
              cpu: 100m

---
apiVersion: v1
kind: Service
metadata:
  name: dov-bear-svc
spec:
  type: ClusterIP
  selector:
    name: dov-bear-po
  ports:
  - port: 80
    targetPort: dov-port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dov-bear-ing
  labels:
    name: dov-bear-ing
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: dov-bear-svc
      port:
        number: 80

  rules:
  - host: dov-bear-139.59.217.220.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: dov-bear-svc
            port: 
              number: 80

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dov-bear-hpa
  labels:
    name: dov-bear-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dov-bear-deploy
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
